# Generated by Django 4.1.2 on 2022-11-13 05:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=250, unique=True, verbose_name='User Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('tel', models.CharField(max_length=250, unique=True, verbose_name='Tel')),
                ('job_title', models.CharField(max_length=250, verbose_name='Job Title')),
                ('remember_me', models.BooleanField(blank=True, default=False)),
                ('level', models.IntegerField(choices=[(0, '0 - New user'), (1, '1 - Verified user'), (2, '2 - Approved User'), (3, '3 - Vip user')], default=0, verbose_name='User Level')),
                ('user_type', models.IntegerField(choices=[(0, '0 - Admin'), (1, '1 - Client'), (2, '2 - Vendor')], default=1, verbose_name='User Type')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(default=1, limit_choices_to={'is_staff': '1'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Manager')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
