# Generated by Django 4.1.2 on 2022-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shippingaddress_companydetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Staff'), (1, 'Client'), (2, 'Vendor')], default=1, verbose_name='User Type'),
        ),
    ]
