# Generated by Django 4.1.2 on 2022-11-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0020_remove_diamond_model_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond_model',
            name='cert_company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Table %'),
        ),
    ]
