# Generated by Django 4.1.2 on 2022-11-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0021_diamond_model_cert_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamond_model',
            name='cert_company',
        ),
    ]
