# Generated by Django 4.1.2 on 2022-11-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0022_remove_diamond_model_cert_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamond_model',
            name='report_link',
            field=models.FloatField(blank=True, default=1, verbose_name='Table %'),
            preserve_default=False,
        ),
    ]
