# Generated by Django 4.1.2 on 2022-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0023_diamond_model_report_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='report_link',
            field=models.URLField(blank=True, verbose_name='Table %'),
        ),
    ]
