# Generated by Django 4.1.2 on 2022-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0024_alter_diamond_model_report_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diamond_model',
            name='cert_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Cert Number'),
        ),
    ]
