# Generated by Django 4.1.2 on 2022-12-19 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0004_rename_cert_number_vedor_diamond_model_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fancy_Vedor_Diamond_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=255, verbose_name='Stock #')),
                ('certificate', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Certificate')),
                ('shape', models.CharField(max_length=255, verbose_name='Shape')),
                ('clarity', models.CharField(max_length=255, verbose_name='Clarity')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('culet', models.CharField(blank=True, max_length=255, verbose_name='Culet')),
                ('cut', models.CharField(blank=True, max_length=255, verbose_name='Cut')),
                ('polish', models.CharField(blank=True, max_length=255, verbose_name='Polish')),
                ('symmetry', models.CharField(blank=True, max_length=255, verbose_name='Symmetry')),
                ('girdle', models.CharField(blank=True, max_length=255, verbose_name='Gridle')),
                ('fluor', models.CharField(blank=True, max_length=255, verbose_name='Fluour')),
                ('measurements', models.CharField(blank=True, max_length=255, verbose_name='Measurements')),
                ('lab', models.CharField(blank=True, max_length=255, verbose_name='Lab')),
                ('photo', models.URLField(blank=True, verbose_name='Image URL')),
                ('video', models.URLField(blank=True, verbose_name='Video URL')),
                ('rap_1ct', models.IntegerField(blank=True, verbose_name='Rap_1ct')),
                ('sale_price', models.IntegerField(blank=True, verbose_name='Sale Price')),
                ('disc', models.FloatField(blank=True, verbose_name='Discount')),
                ('weight', models.FloatField(blank=True, max_length=255, verbose_name='Weight')),
                ('length_mm', models.FloatField(blank=True, verbose_name='Length')),
                ('width', models.FloatField(blank=True, verbose_name='Width')),
                ('depth', models.FloatField(blank=True, verbose_name='Depth')),
                ('lw', models.FloatField(verbose_name='L/W')),
                ('depth_procent', models.FloatField(blank=True, verbose_name='Depth %')),
                ('table_procent', models.FloatField(blank=True, verbose_name='Table %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('best_selling', models.BooleanField(default=False, verbose_name='Best Selling')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='vendor_email')),
            ],
            options={
                'verbose_name': 'Diamond',
                'verbose_name_plural': 'Diamonds',
                'ordering': ['sale_price'],
                'abstract': False,
            },
        ),
    ]
