# Generated by Django 4.1.2 on 2022-12-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_fancy_vedor_diamond_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fancy_vedor_diamond_model',
            options={'ordering': ['sale_price'], 'verbose_name': 'Fancy Diamond', 'verbose_name_plural': 'Fancy Diamonds'},
        ),
    ]
