# Generated by Django 4.1.2 on 2022-12-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_remove_fancy_vedor_diamond_model_rap_1ct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fancy_vedor_diamond_model',
            name='rapaport_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rapaport Price'),
        ),
        migrations.AddField(
            model_name='vedor_diamond_model',
            name='rapaport_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Rapaport Price'),
        ),
    ]
