# Generated by Django 4.1.2 on 2022-12-27 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_fancy_vedor_diamond_model_rap_disc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fancy_vedor_diamond_model',
            old_name='rapaport_price',
            new_name='rap_price',
        ),
        migrations.RenameField(
            model_name='vedor_diamond_model',
            old_name='rapaport_price',
            new_name='rap_price',
        ),
    ]
