# Generated by Django 4.1.2 on 2022-11-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0017_alter_vedor_diamond_model_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vedor_diamond_model',
            name='ref',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Ref'),
        ),
    ]
