# Generated by Django 4.1.2 on 2022-11-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_alter_vedor_diamond_model_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vedor_diamond_model',
            name='key',
        ),
    ]
