# Generated by Django 4.1.2 on 2022-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_remove_vedor_diamond_model_cert_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='vedor_diamond_model',
            name='report_link',
            field=models.URLField(blank=True, verbose_name='Table %'),
        ),
    ]
