# Generated by Django 4.1.2 on 2022-12-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodal',
            name='cart_link',
        ),
    ]
