# Generated by Django 4.1.2 on 2022-12-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartmodal_cart_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodal',
            name='cart_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link To Cart'),
        ),
    ]
