# Generated by Django 4.1.2 on 2022-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_length_orders_diamond_model_length_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_diamond_model',
            name='cert_number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Cert Number'),
        ),
    ]
