# Generated by Django 4.1.2 on 2022-11-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_diamond_model_cert_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_diamond_model',
            name='order_number',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Order Number'),
        ),
    ]
