# Generated by Django 4.1.2 on 2022-12-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_diamond_model_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_diamond_model',
            old_name='cert_number',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='orders_diamond_model',
            old_name='ref',
            new_name='stock',
        ),
    ]
