# Generated by Django 4.1.2 on 2022-12-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_cert_number_orders_diamond_model_certificate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders_diamond_model',
            options={'ordering': ['sale_price'], 'verbose_name': 'Order Diamond', 'verbose_name_plural': 'Orders Diamonds'},
        ),
    ]
