# Generated by Django 4.1.2 on 2022-12-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_diamond_model_fluor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_diamond_model',
            name='rap_1ct',
        ),
        migrations.AddField(
            model_name='orders_diamond_model',
            name='price_per_ct',
            field=models.IntegerField(blank=True, default=0, verbose_name='Price Per CT'),
        ),
        migrations.AddField(
            model_name='orders_diamond_model',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Price'),
        ),
    ]
