# Generated by Django 4.1.2 on 2022-12-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_diamond_model_rapaport_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_diamond_model',
            name='rap_disc',
            field=models.FloatField(blank=True, default=0, verbose_name='Rap Disc'),
        ),
        migrations.AlterField(
            model_name='orders_diamond_model',
            name='disc',
            field=models.FloatField(blank=True, default=0, verbose_name='Disc'),
        ),
    ]
